export default function HeroSection() {
  return (
    <section className="relative pt-24 pb-4 px-4 sm:px-6 text-center overflow-hidden">
      {/* Radial glow */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 flex items-start justify-center"
        style={{ paddingTop: '60px' }}
      >
        <div
          style={{
            width: '700px',
            height: '380px',
            background:
              'radial-gradient(ellipse at center, rgba(124,58,237,0.2) 0%, rgba(124,58,237,0.07) 42%, transparent 68%)',
            filter: 'blur(2px)',
          }}
        />
      </div>

      <div className="relative max-w-4xl mx-auto">
        <p className="label-caps mb-5">Multi-Agent Content Engine</p>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight leading-[1.1] mb-5">
          <span className="text-white block">AEO-Optimized Content,</span>
          <span className="text-gradient-accent block mt-1">Generated by Agents.</span>
        </h1>

        <p className="text-text-secondary text-base sm:text-lg leading-relaxed max-w-2xl mx-auto">
          Neo Scripting is a multi-agent blog engine that writes answer-engine-optimized articles.
          Use it as an API or connect it directly to Claude, Cursor, or any MCP client.
        </p>
      </div>
    </section>
  )
}
